### ISSUE TITLE
Scala embedded leads to a blank page

### ISSUE THREAD

**Issue by manuelleduc** [softlang/metalib#42] opened 2017-10-26 13:30 UTC
Dear metalib maintainers,

I found out opening https://softlang.github.io/metalib/contributions/Scala%20embedded.html in a new tab leads to a blank page.

Clicking on the link "Scala embedded" in the [front page](https://softlang.github.io/metalib/) of metalib is working as expected and display the page.

**Comment by manuelleduc** [comment] 2017-10-26 13:32
This issue might be a duplicate of #35

**Comment by sschauss** [comment] 2017-11-26 17:53
@manuelleduc thank you for reporting this issue and sorry that it took this long for someone to reply. Also, you're right, this is a duplicate of #35 .

**Closed as completed by sschauss** 2017-11-26 17:53 UTC
